#!/bin/bash

filename=$1
command_to_run=$2

if [ ! -e $filename ]; then
	echo "File does not exist"
	exit 1
fi

get_modification_time() {
	echo $(stat -c '%Y' $filename)
}

echo "Watching $filename"
last_change_time=$(get_modification_time)
while true; do
	new_change_time=$(get_modification_time)

	if [ $last_change_time -ne $new_change_time ]; then
		echo "File changed updating"
		tmux kill-session -t testing
		last_change_time=$new_change_time
		tag-general-run-in-tmux testing "$command_to_run && exit"
	fi

	sleep 1
done





