#!/bin/bash

root="$HOME/todos/"

filename="$(tag-date)"
backset=1

while true; do
	filename_pullback="$(tag-date $backset)"

	if [ -f "$root$filename_pullback" ]; then
		break
	fi
tag-create
	((backset++))
done

echo $filename
echo $filename_pullback | sed 's/./^/g'
echo $filename_pullback

if [ ! -f "$root$filename" ]; then
	echo -e "$(tag-date)\n\n" > "$root$filename"
	cat "$root$filename_pullback" | tail -n +3 >> "$root$filename"
fi
