#!/bin/bash

temp_dir=$(mktemp -d)

# options=("testing" "things" "now")
options=$(tmux list-sessions -F "#{session_name}")

cd $temp_dir


for option in $options; do
	echo "Adding option $option"
	touch "$option"
done

cd $temp_dir

read -e -p "Select something: " selection

cd - > /dev/null

rm -rf $temp_dir


