#!/bin/bash
# optional

# lists the commands that you can run in a given directory
if [ ! -e "package.json" ]; then
	echo "File does not exist"
fi


scripts=$(jq -r '.scripts | keys[]' package.json)
if [ $# -eq 0 ]; then
	echo "$scripts"
	exit 0
fi

scripts=$(echo "$scripts" | tag-general-filterer $@)
amount=$(echo "$scripts" | wc -w)

if [ $amount -eq 0 ]; then
	echo "There weren't any scripts that matched your filter"
	exit 0
fi

echo "$scripts"

