#!/bin/bash

root="$HOME/todos/"

filename="$(tag-general-date)"
backset=1

while true; do
	filename_pullback="$(tag-general-date $backset)"

	if [ -f "$root$filename_pullback" ]; then
		break
	fi
	((backset++))
done

echo $filename
echo $filename_pullback | sed 's/./^/g'
echo $filename_pullback

if [ ! -f "$root$filename" ]; then
	echo -e "$(tag-general-date)\n\n" > "$root$filename"
	cat "$root$filename_pullback" | tail -n +3 >> "$root$filename"
fi
