#!/bin/bash

root="$HOME/todos/"

cd "$root" || exit

tag-todo-list
read -e -p "Select a file: " filename

cd - /dev/null

if [ -z $filename ]; then
	filename="$(tag-date).txt"
fi

if [ ! -f "$root$filename" ]; then
	echo "File does not exist"
	exit 1
fi

nvim "$root$filename"
