#!/bin/bash

temp_dir=$(mktemp -d)
cd $temp_dir || exit 1

echo "Options:" 
for param in $@; do
	echo -e "\t$param"
	touch "$param"
done

read -e -p "Select something: " selection

cd - > /dev/null

rm -rf "$temp_dir"

echo "$selection" >&3
