#!/bin/bash
# optional

root=$(tag-meta-parent-directory)

commands=$(ls "$root"/tag-* | xargs -I{} basename {})
commands=$(echo "$commands" | tag-general-filterer "$@" -f "\-")
filter_error=$?
amount=$(echo "$commands" | wc -w)

echo "$commands"

