#!/bin/bash

while true; do
	$1 & 
	process_pid=$!

	(sleep "$2" && kill $process_pid && echo "Restarting process") &
	killer_pid=$!

	cleanup() {
		kill "$process_pid"
		kill "$killer_pid"
		break
	}

	trap cleanup SIGINT

	wait $process_pid
done




