#!/bin/bash
# optional


startingTime=$((30 * 60))
phrase=${2:-stop}

if [ $# -gt 0 ]
then
	if [[ $1 =~ ^[0-9]+$ ]]
	then
		startingTime=$(($1 * 60))
	fi
fi

for ((i = startingTime; i >= 0; i--))
do 
	minutes=$((i / 60))
	seconds=$((i - minutes * 60))
	printf "\r%4d minutes %2d seconds" "$minutes" "$seconds"

	sleep 1
done

tag-general-killer "Spotify"

say -v Bells $phrase

