#!/bin/bash



tag-testing
tag-testing
tag-testing
tag-testing
tag-testing
tag-testing
tag-testing




echo othe rthings

echo things && tag-testing


echo $(tag-testing)

tag-testing
tag-testing
tag-testing
tag-testing
tag-testing
echo testing though


tag-testing
tag-testing
tag-testing


