#!/bin/bash

commands=$(ls /usr/local/bin/tag-* | xargs -I{} basename {})
commands=$(echo "$commands" | tag-general-filterer "$@")
filter_error=$?

if [ $filter_error -ne 0 ]; then
	exit 1
fi

nvim $commands

