#!/bin/bash

# first we need to connect to it and run the save command

echo "Enter ssh password:"
read -s password

SSHLOCATION="joshu@107.179.134.247"

sshpass -p "$password" scp -r $HOME/documents/* $SSHLOCATION:C:/wsl-server-file-backup/server/school
connectionResponse=$?

if [ $connectionResponse -ne 0 ]; then
	echo "Failed to connect to ssh"
	exit 1
fi


sshpass -p "$password" ssh $SSHLOCATION << EOF

wsl bash -c "tag-education-server-sync-with-backup; exit"

EOF



