#!/bin/bash

cd /usr/local/bin/

# we'll take in a filename to rename
current_filename=$1

# we'll also take in the filename that we want to change this to
desired_filename=$2

# we'll then first check if the current on exists
if [ ! -e $current_filename ]; then
	echo "There is no file named '$current_filename'"
	exit 1
fi

# we'll also make sure that the desired filename isn't already taken
if [ -e $desired_filename ]; then
	echo "The desired filename '$desired_filename' is already taken"
	exit 1
fi

# we can now find all files that use the old name of that script
# occurances=$(grep -o "tag[1-9]" $(ls tag-*))
occurances=$(grep "$current_filename" $(ls tag-*))

if [ -n "$occurances" ]; then
	echo "Found the following occurances of '$current_filename' that need changing"
	echo "$occurances"

	for file in tag-*; do
		if grep -q "$current_filename" "$file"; then
			cp "$file" "$file.bak"

			sed -i "" "s/$current_filename/$desired_filename/g" "$file"

			echo "Updated $file"

			diff --side-by-side "$file.bak" "$file"
		fi
	done
fi

echo "Renaming '$current_filename' to '$desired_filename'"

mv $current_filename $desired_filename

