#!/bin/bash

inputs=$(cat)

input_params=()
verbose=false
capture_delimiter=false
delimiter=''

for param in "$@"; do
	if [ "$capture_delimiter" = true ]; then
		delimiter="$param"
		capture_delimiter=false
	elif [ "$param" = "-f" ] || [ "$param" = "--filter" ]; then
		capture_delimiter=true
	elif [ "$param" = "-v" ] || [ "$param" = "--verbose" ]; then
		verbose=true
	else
		input_params+=("$param")
	fi
done

amount=0
done=false
for param in "${input_params[@]}"; do
	if [ "$done" = true ]; then
		if [ "$verbose" = true ]; then
			>&2 echo "WARNING: You have extra filter params"
		fi
		break
	fi

	inputs=$(echo "$inputs" | grep -E "$delimiter$param")
	amount=$(echo "$inputs" | wc -w)

	if [ $amount -eq 1 ]; then
		done=true
	fi
done

echo "$inputs"
