#!/bin/bash
# optional

if [ -z "$1" ]; then
	# temp_dir=$(mktemp -d)

	options=$(tmux list-sessions -F "#{session_name}")

	tag-meta-output-capture "tag-general-autocompleter \"${options[@]}\""
	selection=$(tag-meta-output-retrieve)

	echo "You selected: $selection"

	tmux attach -t $selection
else
	tmux attach -t $1
fi


