#!/bin/bash

temp_dir=$(mktemp -d)
cd $temp_dir || exit 1

>&2 echo "Options:" 
for param in $@; do
	>&2 echo -e "\t$param"
	touch "$param"
done

read -e -p "Select something: " selection

cd - > /dev/null

rm -rf "$temp_dir"

>&3 echo "$selection"
