#!/bin/bash

root="$HOME/todos/"
filename="$1"

if [ -z "$filename" ]; then
 	# didn't provide name, default to today's date
	filename="$(tag-date).txt"
fi

echo $filename

if [ ! -f "$root$filename" ]; then
	echo "Does not exist"
	exit 1
fi

nvim "$root$filename"
